site_name: Test Material
site_description: Bla, bla, bla
site_url: https://astrowo.github.io/testmaterial/

# Theme
theme:
  name: material
  custom_dir: overrides
  language: hu
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.top
  palette: 
    - scheme: default
      primary: teal
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

# Social
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/4kelly
      name: squidfunk on Twitter
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/4kelly_
      name: squidfunk on Twitter
  generator: false    # Made with Material for MkDocs - in footer
  version:
    provider: mike

# Repository
repo_url: https://github.com/astrowo/astrowo
repo_name: astrowo
edit_uri: ""

copyright: Copyright &copy; 2016 - 2020 Bla Bla bla 2