site_name: Test Material

theme:
  name: material

# Social
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/4kelly
      name: squidfunk on Twitter
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/4kelly_
      name: squidfunk on Twitter
  generator: false
  version:
    provider: mike